// @tools loogle_mathlib
// Experimental arm (PLAN.md block A): structure-based search — the public Loogle API
// over the compiled Mathlib environment, vs lean-search's semantic index and
// lean-grep's source text. Searches elaborated declarations by name substring,
// mentioned constants, or type pattern, so it sees generated names (`to_additive`,
// aliases) that never appear in source. Like the other two arms, the whole prompt
// delta lives in the tool description below.

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ToolFailure } from "../runner/common.js";

const API = "https://loogle.lean-lang.org/json";

// Hits are filtered against the pinned compiled environment before the agent sees
// them — the opposite decision from search_mathlib, for a quantitative reason: the
// public Loogle instance tracks current Mathlib, ~800 commits past our pin, and a
// 2,559-name sample (2026-07-31) put the skew at 9.5% — names Loogle confirms that do
// not exist here — vs LeanSearch's measured 0.2%. The no-filter argument ("a filter
// makes the arm curated-X rather than X") was priced at 0.2%; at 9.5% the tool's core
// promise — a returned name exists — is what breaks. Filtering only ever removes
// false-presents; the reverse direction (our names Loogle no longer knows) sampled at
// 1/30, a compiler-internal lemma. A locally-built Loogle would have zero skew and is
// the pre-registered upgrade if this arm wins; dropped names stay in `details` so
// Loogle-as-deployed is reconstructible from the logs.
// problems/env-names.txt is derived (gitignored, like stmt-types.json): every
// non-internal constant of the resident environment, regenerated by
// scripts/dump-env-names.mjs against a running lean server.
const ENV_NAMES_FILE = join(dirname(fileURLToPath(import.meta.url)), "..", "problems", "env-names.txt");
let envNames: Set<string> | null = null;
function pinnedNames(): Set<string> {
  if (!envNames) {
    let txt: string;
    try {
      txt = readFileSync(ENV_NAMES_FILE, "utf8");
    } catch {
      // Fail loudly and per-call: a run that silently skipped the filter would be a
      // different arm than the one SEARCH.md defines. run.js preflights this file for
      // loogle combos, so reaching here mid-run means it was deleted underneath us.
      // The message is model-visible (pi sends ToolFailure text as the tool result),
      // so it names no harness paths and no filter: regenerate with
      // `node scripts/dump-env-names.mjs` (lean server up).
      throw new ToolFailure("loogle_mathlib is unavailable (harness misconfiguration).");
    }
    envNames = new Set(txt.split("\n").filter(Boolean));
  }
  return envNames;
}

// Fixed result count, deliberately not a tool parameter — same reasoning as the other
// arms. 10 like grep, not 6 like semantic: Loogle hits arrive in module import order,
// not relevance order, so a low cap can drop the right hit arbitrarily.
const NUM_RESULTS = 10;

// One docstring line, capped — parallel to semantic's informal name, not a document.
const DOC_MAX = 160;

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "loogle_mathlib",
    label: "Loogle Mathlib",
    // Capability, query syntax, and return shape — no when/why steering, mirroring the
    // other two arms. Syntax has to be taught (it is Loogle's, not ours): without it
    // the arm measures syntax guessing rather than structure search.
    description:
      "Loogle: search Mathlib by name or by type structure. Query forms, combinable with commas: " +
      'a quoted string ("mul_pow") matches declaration names containing it; a constant name ' +
      "(Real.sin) matches declarations whose type mentions it; a term pattern with wildcards — " +
      "_ for anything, ?a to require the same thing at every ?a — matches declarations whose " +
      "type contains a subterm of that shape ((_ * _) ^ _, List.map _ (List.map _ _)); a " +
      "pattern starting with ⊢ (⊢ tsum _ = _ * tsum _) matches only against the conclusion. " +
      "Identifiers in patterns must be real constants or wildcards, not free variables. " +
      "Returns matching declarations with their fully-qualified names and type signatures.",
    promptSnippet: "loogle_mathlib - search Mathlib by name or type structure",
    parameters: Type.Object({
      query: Type.String({ description: "Loogle query (quoted name fragment, constant, or term pattern)" }),
    }),
    async execute(_toolCallId, params, signal) {
      const ac = new AbortController();
      const t = setTimeout(() => ac.abort(), 30_000);
      signal?.addEventListener("abort", () => ac.abort());
      try {
        const resp = await fetch(`${API}?q=${encodeURIComponent(params.query)}`, {
          headers: { "User-Agent": "CMP-experiment (mb2617@cam.ac.uk)" },
          signal: ac.signal,
        });
        if (!resp.ok) {
          throw new ToolFailure(`Loogle API error: HTTP ${resp.status}`);
        }
        const data = (await resp.json()) as {
          error?: string;
          suggestions?: string[];
          count?: number;
          header?: string;
          heartbeats?: number;
          hits?: { name: string; type: string; module: string; doc: string | null }[];
        };
        // A query Loogle cannot parse or elaborate is a bad pattern, not a zero-hit
        // result — same classification as grep's bad regex. Loogle's message (plus its
        // own suggestions, when it offers any) is the actionable answer.
        if (data.error) {
          // Suggestions are capped like results are: Loogle offered 27 rewrites for one
          // malformed pattern in probing, and an error message is not the place to spend
          // a result's worth of tokens.
          const sugs = (data.suggestions ?? []).slice(0, 8);
          const sug = sugs.length ? ` Did you mean: ${sugs.join(", ")}` : "";
          // "Unknown identifier" is a well-formed existence probe whose answer is "no
          // such constant" — a RESULT, mirroring grep's zero-hit answer to the same
          // confirmation question (the smoke run showed 32 of 56 rejections were
          // exactly this shape). Parse errors and ill-typed patterns ("Function
          // expected at ...") remain failures, the analogue of grep's bad regex.
          if (/unknown (identifier|constant)/i.test(data.error)) {
            return {
              content: [{ type: "text", text: `No results: ${data.error}.${sug}` }],
              details: { count: 0, queryError: data.error },
            };
          }
          throw new ToolFailure(`Loogle rejected the query: ${data.error}.${sug}`);
        }
        const raw = data.hits ?? [];
        const pinned = pinnedNames();
        const hits = raw.filter((h) => pinned.has(h.name));
        const dropped = raw.length - hits.length;
        if (hits.length === 0)
          return {
            content: [{ type: "text", text: "No results." }],
            details: { count: 0, rawCount: data.count ?? raw.length, dropped, droppedNames: raw.slice(0, 40).map((h) => h.name) },
          };
        const shown = hits.slice(0, NUM_RESULTS);
        const lines = shown.map((h) => {
          const doc = h.doc ? ` — ${h.doc.split("\n")[0].trim().slice(0, DOC_MAX)}` : "";
          // `type` already carries the binders-plus-colon suffix that follows the name
          // (" (a b n : ℕ) : (a * b) ^ n = ..."), so the name concatenates directly —
          // a literal ` : ` here doubled the colon on every hit.
          return `• ${h.name}${h.type}${doc}`;
        });
        // Loogle's header line is NOT passed through: its counts are pre-filter, so
        // beside filtered bullets it would claim declarations the agent can never see —
        // and phantom counts induce narrowing calls hunting for hits that do not exist
        // here. The only count shown is the filtered one actually in hand; "+" marks
        // that Loogle itself truncated (it returns at most 200), so the true total is
        // larger. Bare bullets otherwise, mirroring search_mathlib.
        const plus = (data.count ?? raw.length) > raw.length ? "+" : "";
        const more =
          hits.length > NUM_RESULTS ? [`note: showing ${shown.length} of ${hits.length}${plus} — narrow the query.`] : [];
        return {
          content: [{ type: "text", text: [...lines, ...more].join("\n") }],
          // Log-only (pi sends the model `content`, never `details`): modules stay out
          // of the model-visible surface — a path signal induces reads this environment
          // cannot serve (see commit 24ed9ae) — and the full hit list plus
          // heartbeats is kept for skew and cost analysis.
          details: {
            count: hits.length,
            rawCount: data.count ?? raw.length,
            dropped,
            droppedNames: dropped ? raw.filter((h) => !pinned.has(h.name)).slice(0, 40).map((h) => h.name) : [],
            shown: shown.length,
            heartbeats: data.heartbeats ?? null,
            hits: hits.map((h) => ({ name: h.name, module: h.module })),
          },
        };
      } catch (e: any) {
        if (e instanceof ToolFailure) throw e;
        throw new ToolFailure(`Loogle request failed: ${e?.message ?? e}`);
      } finally {
        clearTimeout(t);
      }
    },
  });
}
