#!/usr/bin/env python3
"""Regenerate RUNS.md — the ledger of every run, what it solved, and what it cost.

Auto-generated, so it can be re-run after every cell rather than hand-maintained.
Costs are cost_std throughout: billed_usd is an account-wide balance delta and is
meaningless wherever runs overlapped or a top-up landed mid-run (semantic-0805 reads
-$155.69 for exactly that reason).

Grid cells reach n=90 by gluing the easy3 supplement onto the safe87 cell, per PLAN's
2026-08-08/09 decisions. Comparison conventions — which cost estimand, the budget
curve, the noise floor — are COMPARE.md's; this file only applies them.

    ./scripts/run-report.py [--out RUNS.md]
"""

import json, os, glob, re, sys
from math import comb

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = sys.argv[sys.argv.index("--out") + 1] if "--out" in sys.argv else os.path.join(ROOT, "RUNS.md")

# The arms of the FATE-X grid, and where each one's problems live. A cell is the
# safe87 run plus its glued easy3 supplement, or a native safe90 run.
CELLS = {
    "base":        ["base-fatex87-0807", "base-fatex87-0807-easy3"],
    "grep":        ["grep-fatex87-0807", "grep-fatex87-0807-easy3"],
    "semantic":    ["semantic-fatex87-0807", "semantic-fatex87-0807-easy3"],
    "snippetonly": ["snippetonly-fatex90-0807"],
    "grep r2":     ["grep-fatex90-0807-r2"],
    "snippet":     ["snippet-fatex90-0807"],
    "base r2":     ["base-fatex90-0807-r2"],
    "spawn":       ["spawn-fatex90-0807"],
    "spawnfacts":  ["spawnfacts-fatex90-0807"],
    "snippetfacts": ["snippetfacts-fatex90-0812"],
    "snippet r2":  ["snippet-fatex90-0807-r2"],
    "snippetonly r2": ["snippetonly-fatex90-0807-r2"],
    "basequote":   ["basequote-fatex90-0813"],
}
# Same-arm replicate pairs — the noise floor pools over all of them.
REPLICATE_PAIRS = [("grep", "grep r2"), ("base", "base r2"), ("snippet", "snippet r2")]
PRE_FREEZE = ["grep-fatex87-0805", "semantic-fatex87-0805"]
PILOTS = ["snippet-fatex10-0804", "spawn-fatex10-0804", "spawnfacts-fatex10-0804",
          "lean-search-fatex-pilot10-0802", "lean-search-think-fateh81-0727",
          "lean-grep-fateh50-0730b", "lean-search-fateh20-0726"]


def rows(rid):
    # Prefer the most-patched glued view of the cell (originals never edited):
    # cwrerun-patched (context-wall reruns; stacks on the fgrerun view) >
    # fgrerun-patched (post-false-green) > raw. Same chain as the chart scripts.
    p = os.path.join(ROOT, "results", rid, "results.jsonl")
    for suffix in ("-cwrerun-patched.results.jsonl", "-fgrerun-patched.results.jsonl"):
        patched = os.path.join(ROOT, "results", rid + suffix)
        if os.path.exists(patched):
            p = patched
            break
    if not os.path.exists(p):
        return []
    out = []
    for l in open(p):
        try:
            out.append(json.loads(l))
        except ValueError:
            pass
    return out


def summary(rid):
    p = os.path.join(ROOT, "results", rid, "summary.json")
    return json.load(open(p)) if os.path.exists(p) else None


def total(rid):
    p = os.path.join(ROOT, "results", rid, "run.json")
    return len(json.load(open(p))["problems"]) if os.path.exists(p) else None


def cell(name):
    """A cell as {problem: record}, plus whether every constituent run finished."""
    d, done, tot = {}, True, 0
    for rid in CELLS[name]:
        for r in rows(rid):
            d[r["problem"]] = r
        if summary(rid) is None:
            done = False
        tot += total(rid) or 0
    return d, done, tot


def firstc(r):
    f = (r.get("high_water") or {}).get("first")
    return f["cost_std"] if (f and f.get("solved")) else float("inf")


def mcnemar(b, c):
    n = b + c
    if n == 0:
        return 1.0
    return min(1.0, 2 * sum(comb(n, k) for k in range(0, min(b, c) + 1)) / 2 ** n)


cells = {k: cell(k) for k in CELLS}
# Comparisons run on COMPLETE cells only: a partial cell in the intersection would
# silently shrink every denominator below.
done_cells = {k: v for k, v in cells.items() if v[1] and v[0]}
common = sorted(set.intersection(*[set(d) for d, _, _ in done_cells.values()])) if done_cells else []

# The block between the summary markers is hand-maintained (meeting summaries,
# implications) and is carried over verbatim on every regeneration.
hand = ""
if os.path.exists(OUT):
    m = re.search(r"<!-- summary:begin -->.*?<!-- summary:end -->", open(OUT).read(), re.S)
    if m:
        hand = m.group(0)

L = []
w = L.append

w("# Run ledger")
w("")
w("Auto-generated by `scripts/run-report.py` — re-run it after every cell rather than")
w("editing here. Costs are **cost_std**; `billed_usd` is an account-wide balance delta and")
w("is meaningless wherever runs overlapped or a top-up landed mid-run. Comparison")
w("conventions are `COMPARE.md`'s. The block between the `summary:begin/end` markers is")
w("hand-maintained and survives regeneration; everything else is overwritten.")
w("")
if hand:
    w(hand)
    w("")

# ---------------------------------------------------------------- grid cells
w("## The FATE-X grid (freeze 0807)")
w("")
w("Cells reach n=90 by gluing the easy3 supplement onto the safe87 run; `grep r2` and")
w("`snippetonly` run safe90 natively.")
w("")
w("**AUC** is the area under the arm's solve-count-vs-budget curve from $0 to the $1")
w("cap: every solve contributes (cap − first-proof cost), so a $0.05 solve adds ~0.95,")
w("a solve at the cap adds ~0, and an unsolved problem adds nothing. Max 90 (every")
w("problem solved for free). It rewards solving *cheaply*, not just solving — two arms")
w("with equal solve counts differ in AUC if one gets its proofs earlier in the budget.")
w("")
w("| arm | solved | n | spend | $/solve | at-cap | AUC | status |")
w("|---|---|---|---|---|---|---|---|")
for name, (d, done, tot) in cells.items():
    if not d:
        continue
    n = len(d)
    sol = [p for p in d if d[p]["solved"]]
    sp = sum(d[p]["cost_std"] or 0 for p in d)
    cap = sum(1 for p in d if not d[p]["solved"] and (d[p]["cost_std"] or 0) > 0.95)
    auc = sum(1 - firstc(d[p]) for p in sol if firstc(d[p]) <= 1)
    st = "complete" if done else f"**running {n}/{tot}**"
    per = f"${sp/len(sol):.3f}" if sol else "—"
    w(f"| {name} | {len(sol)} | {n} | ${sp:.2f} | {per} | {cap} | {auc:.1f} | {st} |")
w("")
if any(not done for _, done, _ in cells.values()):
    w("> Rows marked running are partial and **not comparable** — runs process the list in")
    w("> order and the head of FATE-X is the cheap end, so partial solve rates read high.")
    w("")

# ---------------------------------------------------------------- budget curve
if common:
    w("## Solve rate vs budget (simulated cutoffs)")
    w("")
    w("Solves = first-proof cost ≤ cap; spend = Σ min(end cost, cap). Exact for any cap ≤ $1,")
    w("since a $1 run censors downward for free. Assumes an attempt killed after reaching a")
    w("verified proof still grades solved (high-water scan: 213/213).")
    w("")
    names = list(done_cells)
    w("| cap | " + " | ".join(names) + " | spread |")
    w("|---" * (len(names) + 2) + "|")
    for c in [x / 100 for x in range(5, 101, 5)]:
        vals, sols = [], []
        for k in names:
            d = cells[k][0]
            s = sum(1 for p in common if firstc(d[p]) <= c)
            sp = sum(min(d[p]["cost_std"] or 0, c) for p in common)
            vals.append(f"{s} / ${sp:.2f}")
            sols.append(s)
        w(f"| ${c:.2f} | " + " | ".join(vals) + f" | {max(sols)-min(sols)} |")
    w("")
    w(f"On the {len(common)} problems all arms have finished.")
    w("")

# ---------------------------------------------------------------- noise floor
flips, pair_lines = [], []
for a1, a2 in REPLICATE_PAIRS:
    d1, d2 = cells.get(a1, ({}, 0, 0))[0], cells.get(a2, ({}, 0, 0))[0]
    shared = sorted(set(d1) & set(d2))
    if len(shared) < 85:
        continue
    only1 = [p for p in shared if d1[p]["solved"] and not d2[p]["solved"]]
    only2 = [p for p in shared if d2[p]["solved"] and not d1[p]["solved"]]
    F = len(only1) + len(only2)
    flips.append(F)
    pair_lines.append((a1, a2, F, len(shared), only1, only2))
if pair_lines:
    w("## The noise floor — same arm, run 1 vs run 2")
    w("")
    w("Same arm, same freeze, same list. Every flip here is a problem whose outcome is a")
    w("coin, and it is the denominator of every comparison in the grid:")
    w("**Var(difference in solve counts) = F / k** for k replicates per arm.")
    w("")
    for a1, a2, F, n, only1, only2 in pair_lines:
        w(f"- **{a1} vs {a2}: {F} flips on {n}** ({n-F} agree)")
        w(f"  - r1 solved, r2 did not: {', '.join(only1) if only1 else '—'}")
        w(f"  - r2 solved, r1 did not: {', '.join(only2) if only2 else '—'}")
    F = sum(flips) / len(flips)
    w(f"- pooled over {len(pair_lines)} replicate pairs: **F = {F:.1f}**")
    w("")
    w("| k replicates/arm | SE (solves) | 95% CI half-width | min detectable gap |")
    w("|---|---|---|---|")
    for k in [1, 2, 3, 5]:
        se = (F / k) ** 0.5
        w(f"| {k} | {se:.2f} | ±{1.96*se:.1f} | {2.8*se:.1f} |")
    w("")

# ---------------------------------------------------------------- pairwise
if common:
    w("## Pairwise discordance")
    w("")
    w("b = problems only the left arm solved, c = only the right arm; problems both or")
    w("neither solved carry no information and drop out. p is the probability of a b/c")
    w("split at least this uneven if every discordant problem were a fair coin — small p")
    w("means the imbalance is unlikely to be luck, and p = 1.0 means a dead-even split.")
    w("")
    w("| comparison | b / c | discordant | exact McNemar |")
    w("|---|---|---|---|")
    names = list(done_cells)
    for i, a in enumerate(names):
        for bn in names[i + 1:]:
            da, db = cells[a][0], cells[bn][0]
            b = sum(1 for p in common if da[p]["solved"] and not db[p]["solved"])
            c = sum(1 for p in common if db[p]["solved"] and not da[p]["solved"])
            w(f"| {a} vs {bn} | {b} / {c} | {b+c} | {mcnemar(b,c):.4f} |")
    w("")
    w("Read against the noise floor above before calling any of these an effect.")
    w("")

    # ------------------------------------------------------------ who flipped
    names = list(done_cells)
    contested = [p for p in common
                 if 0 < sum(1 for k in names if cells[k][0][p]["solved"]) < len(names)]
    w("## The contested problems")
    w("")
    w(f"{len(contested)} of {len(common)} problems are solved by some arms and not others —")
    w(f"the only ones carrying information. {sum(1 for p in common if all(cells[k][0][p]['solved'] for k in names))}")
    w("are solved by every arm and")
    w(f"{sum(1 for p in common if not any(cells[k][0][p]['solved'] for k in names))} by none.")
    w("")
    w("| problem | " + " | ".join(names) + " |")
    w("|---" * (len(names) + 1) + "|")
    for p in contested:
        marks = ["✓" if cells[k][0][p]["solved"] else "·" for k in names]
        w(f"| {p} | " + " | ".join(marks) + " |")
    w("")

# ---------------------------------------------------------------- all runs
w("## Every run on record")
w("")
w("n / solved / cost_std are keep-last over the run dir's own `results.jsonl` (resumed")
w("rows carry cumulative spend, so this includes resume-segment costs that the original")
w("summary.json predates). ⟳ = run was resumed after the 0816 402 outage; runs without")
w("a finished date closed without a summary (killed or resume-only dirs).")
w("")


def ledger_row(rid):
    """(combo, n, solved, cost, finished, resumed) — keep-last over the dir's own
    results.jsonl (summary.json undercounts resumed dirs), summaries for metadata."""
    s = summary(rid)
    sr = os.path.join(ROOT, "results", rid, "summary-resume.json")
    resume = json.load(open(sr)) if os.path.exists(sr) else None
    last = {}
    p = os.path.join(ROOT, "results", rid, "results.jsonl")
    if os.path.exists(p):
        for l in open(p):
            try:
                r = json.loads(l)
                last[r["problem"]] = r
            except ValueError:
                pass
    meta = s or resume or {}
    if not meta.get("combo"):
        rj = os.path.join(ROOT, "results", rid, "run.json")
        if os.path.exists(rj):
            meta = dict(meta, combo=json.load(open(rj)).get("combo"))
    combo = ",".join(meta.get("combo") or []) or "base"
    if not last:
        return (combo, meta.get("problems"), meta.get("solved"),
                meta.get("cost_std") or 0, (meta.get("finished_at") or "")[:10], bool(resume))
    finished = (s or {}).get("finished_at") or (resume or {}).get("finished_at") or ""
    if resume and (resume.get("finished_at") or "") > ((s or {}).get("finished_at") or ""):
        finished = resume["finished_at"]
    return (combo, len(last), sum(1 for r in last.values() if r.get("solved")),
            sum(r.get("cost_std") or 0 for r in last.values()),
            finished[:10] if s or resume else "—", bool(resume))


dirs = sorted({os.path.basename(os.path.dirname(f)) for f in
               glob.glob(os.path.join(ROOT, "results", "*", "summary.json")) +
               glob.glob(os.path.join(ROOT, "results", "*", "summary-resume.json")) +
               glob.glob(os.path.join(ROOT, "results", "*", "results.jsonl"))})
allrun = [(rid, ledger_row(rid)) for rid in dirs]
smoke = [(r, v) for r, v in allrun if r.startswith(("smoke", "ga-smoke", "preflight", "_", "retry-test", "wifi-test"))]
main = [(r, v) for r, v in allrun if not r.startswith(("smoke", "ga-smoke", "preflight", "_", "retry-test", "wifi-test"))]

w("| run | combo | n | solved | cost_std | finished |")
w("|---|---|---|---|---|---|")
for rid, (combo, n, sol, cost, fin, resumed) in sorted(main, key=lambda x: (x[1][4] == "—", x[1][4], x[0])):
    mark = " ⟳" if resumed else ""
    w(f"| {rid}{mark} | {combo} | {n} | {sol} | ${cost:.2f} | {fin or '—'} |")
# in-flight
for name, (d, done, tot) in cells.items():
    if not done and d:
        for rid in CELLS[name]:
            if summary(rid) is None and rows(rid):
                rr = rows(rid)
                w(f"| {rid} | *in flight* | {tot} | {sum(1 for r in rr if r['solved'])} (of "
                  f"{len(rr)} done) | ${sum(r.get('cost_std') or 0 for r in rr):.2f} | — |")
w("")
sm = sum(v[3] for _, v in smoke)
w(f"Plus {len(smoke)} smoke/probe runs totalling ${sm:.2f}.")
w("")
triage = [d for d in glob.glob(os.path.join(ROOT, "results", "triage-*"))
          if os.path.isdir(d) and not os.path.exists(os.path.join(d, "results.jsonl"))]
if triage:
    w(f"Not ledgered: {len(triage)} triage-judge dirs (arm killed 2026-08-16; per-attempt")
    w("judge data only, no results.jsonl — spend not tracked here).")
    w("")

grand = sum(v[3] for _, v in allrun)
inflight = sum(sum(r.get("cost_std") or 0 for r in rows(rid))
               for name, (d, done, _) in cells.items() if not done
               for rid in CELLS[name] if summary(rid) is None)
w(f"**Total cost_std across every run: ${grand + inflight:.2f}** "
  f"(${grand:.2f} on record + ${inflight:.2f} in flight).")
w("")

open(OUT, "w").write("\n".join(L) + "\n")
print(f"wrote {OUT} ({len(L)} lines)")
