#!/usr/bin/env python3
"""Regenerate RUNS.md — the ledger of every run, what it solved, and what it cost.

Auto-generated, so it can be re-run after every cell rather than hand-maintained.
Costs are cost_std throughout: billed_usd is an account-wide balance delta and is
meaningless wherever runs overlapped or a top-up landed mid-run (semantic-0805 reads
-$155.69 for exactly that reason).

Grid cells reach n=90 by gluing the easy3 supplement onto the safe87 cell, per PLAN's
2026-08-08/09 decisions. Comparison conventions — which cost estimand, the budget
curve, the noise floor — are COMPARE.md's; this file only applies them.

    ./scripts/run-report.py [--out RUNS.md]
"""

import json, os, glob, sys
from math import comb

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = sys.argv[sys.argv.index("--out") + 1] if "--out" in sys.argv else os.path.join(ROOT, "RUNS.md")

# The arms of the FATE-X grid, and where each one's problems live. A cell is the
# safe87 run plus its glued easy3 supplement, or a native safe90 run.
CELLS = {
    "base":        ["base-fatex87-0807", "base-fatex87-0807-easy3"],
    "grep":        ["grep-fatex87-0807", "grep-fatex87-0807-easy3"],
    "semantic":    ["semantic-fatex87-0807", "semantic-fatex87-0807-easy3"],
    "snippetonly": ["snippetonly-fatex90-0807"],
    "grep r2":     ["grep-fatex90-0807-r2"],
}
PRE_FREEZE = ["grep-fatex87-0805", "semantic-fatex87-0805"]
PILOTS = ["snippet-fatex10-0804", "spawn-fatex10-0804", "spawnfacts-fatex10-0804",
          "lean-search-fatex-pilot10-0802", "lean-search-think-fateh81-0727",
          "lean-grep-fateh50-0730b", "lean-search-fateh20-0726"]


def rows(rid):
    p = os.path.join(ROOT, "results", rid, "results.jsonl")
    if not os.path.exists(p):
        return []
    out = []
    for l in open(p):
        try:
            out.append(json.loads(l))
        except ValueError:
            pass
    return out


def summary(rid):
    p = os.path.join(ROOT, "results", rid, "summary.json")
    return json.load(open(p)) if os.path.exists(p) else None


def total(rid):
    p = os.path.join(ROOT, "results", rid, "run.json")
    return len(json.load(open(p))["problems"]) if os.path.exists(p) else None


def cell(name):
    """A cell as {problem: record}, plus whether every constituent run finished."""
    d, done, tot = {}, True, 0
    for rid in CELLS[name]:
        for r in rows(rid):
            d[r["problem"]] = r
        if summary(rid) is None:
            done = False
        tot += total(rid) or 0
    return d, done, tot


def firstc(r):
    f = (r.get("high_water") or {}).get("first")
    return f["cost_std"] if (f and f.get("solved")) else float("inf")


def mcnemar(b, c):
    n = b + c
    if n == 0:
        return 1.0
    return min(1.0, 2 * sum(comb(n, k) for k in range(0, min(b, c) + 1)) / 2 ** n)


cells = {k: cell(k) for k in CELLS}
common = sorted(set.intersection(*[set(d) for d, _, _ in cells.values()])) if cells else []

L = []
w = L.append

w("# Run ledger")
w("")
w("Auto-generated by `scripts/run-report.py` — re-run it after every cell rather than")
w("editing here. Costs are **cost_std**; `billed_usd` is an account-wide balance delta and")
w("is meaningless wherever runs overlapped or a top-up landed mid-run. Comparison")
w("conventions are `COMPARE.md`'s.")
w("")

# ---------------------------------------------------------------- grid cells
w("## The FATE-X grid (freeze 0807)")
w("")
w("Cells reach n=90 by gluing the easy3 supplement onto the safe87 run; `grep r2` and")
w("`snippetonly` run safe90 natively.")
w("")
w("| arm | solved | n | spend | $/solve | at-cap | AUC | status |")
w("|---|---|---|---|---|---|---|---|")
for name, (d, done, tot) in cells.items():
    if not d:
        continue
    n = len(d)
    sol = [p for p in d if d[p]["solved"]]
    sp = sum(d[p]["cost_std"] or 0 for p in d)
    cap = sum(1 for p in d if not d[p]["solved"] and (d[p]["cost_std"] or 0) > 0.95)
    auc = sum(1 - firstc(d[p]) for p in sol if firstc(d[p]) <= 1)
    st = "complete" if done else f"**running {n}/{tot}**"
    per = f"${sp/len(sol):.3f}" if sol else "—"
    w(f"| {name} | {len(sol)} | {n} | ${sp:.2f} | {per} | {cap} | {auc:.1f} | {st} |")
w("")
if any(not done for _, done, _ in cells.values()):
    w("> Rows marked running are partial and **not comparable** — runs process the list in")
    w("> order and the head of FATE-X is the cheap end, so partial solve rates read high.")
    w("")

# ---------------------------------------------------------------- budget curve
if common:
    w("## Solve rate vs budget (simulated cutoffs)")
    w("")
    w("Solves = first-proof cost ≤ cap; spend = Σ min(end cost, cap). Exact for any cap ≤ $1,")
    w("since a $1 run censors downward for free. Assumes an attempt killed after reaching a")
    w("verified proof still grades solved (high-water scan: 213/213).")
    w("")
    names = [k for k in cells if cells[k][0]]
    w("| cap | " + " | ".join(names) + " | spread |")
    w("|---" * (len(names) + 2) + "|")
    for c in [0.10, 0.25, 0.50, 0.75, 1.00]:
        vals, sols = [], []
        for k in names:
            d = cells[k][0]
            s = sum(1 for p in common if firstc(d[p]) <= c)
            sp = sum(min(d[p]["cost_std"] or 0, c) for p in common)
            vals.append(f"{s} / ${sp:.2f}")
            sols.append(s)
        w(f"| ${c:.2f} | " + " | ".join(vals) + f" | {max(sols)-min(sols)} |")
    w("")
    w(f"On the {len(common)} problems all arms have finished.")
    w("")

# ---------------------------------------------------------------- noise floor
gr1, gr2 = cells.get("grep", ({}, 0, 0))[0], cells.get("grep r2", ({}, 0, 0))[0]
shared = sorted(set(gr1) & set(gr2))
if shared:
    only1 = [p for p in shared if gr1[p]["solved"] and not gr2[p]["solved"]]
    only2 = [p for p in shared if gr2[p]["solved"] and not gr1[p]["solved"]]
    F = len(only1) + len(only2)
    w("## The noise floor — grep run 1 vs run 2")
    w("")
    w("Same arm, same freeze, same list. Every flip here is a problem whose outcome is a")
    w("coin, and it is the denominator of every comparison in the grid:")
    w("**Var(difference in solve counts) = F / k** for k replicates per arm.")
    w("")
    w(f"- **{F} flips on {len(shared)} problems** ({len(shared)-F} agree)")
    w(f"- r1 solved, r2 did not: {', '.join(only1) if only1 else '—'}")
    w(f"- r2 solved, r1 did not: {', '.join(only2) if only2 else '—'}")
    if len(shared) >= 85:
        w("")
        w("| k replicates/arm | SE (solves) | 95% CI half-width | min detectable gap |")
        w("|---|---|---|---|")
        for k in [1, 2, 3, 5]:
            se = (F / k) ** 0.5
            w(f"| {k} | {se:.2f} | ±{1.96*se:.1f} | {2.8*se:.1f} |")
    else:
        w(f"- projected to the full 90 once r2 finishes; {len(shared)} problems is a partial read")
    w("")

# ---------------------------------------------------------------- pairwise
if common:
    w("## Pairwise discordance")
    w("")
    w("| comparison | b / c | discordant | exact McNemar |")
    w("|---|---|---|---|")
    names = [k for k in cells if cells[k][0]]
    for i, a in enumerate(names):
        for bn in names[i + 1:]:
            da, db = cells[a][0], cells[bn][0]
            b = sum(1 for p in common if da[p]["solved"] and not db[p]["solved"])
            c = sum(1 for p in common if db[p]["solved"] and not da[p]["solved"])
            w(f"| {a} vs {bn} | {b} / {c} | {b+c} | {mcnemar(b,c):.4f} |")
    w("")
    w("Read against the noise floor above before calling any of these an effect.")
    w("")

    # ------------------------------------------------------------ who flipped
    names = [k for k in cells if cells[k][0]]
    contested = [p for p in common
                 if 0 < sum(1 for k in names if cells[k][0][p]["solved"]) < len(names)]
    w("## The contested problems")
    w("")
    w(f"{len(contested)} of {len(common)} problems are solved by some arms and not others —")
    w(f"the only ones carrying information. {sum(1 for p in common if all(cells[k][0][p]['solved'] for k in names))}")
    w("are solved by every arm and")
    w(f"{sum(1 for p in common if not any(cells[k][0][p]['solved'] for k in names))} by none.")
    w("")
    w("| problem | " + " | ".join(names) + " |")
    w("|---" * (len(names) + 1) + "|")
    for p in contested:
        marks = ["✓" if cells[k][0][p]["solved"] else "·" for k in names]
        w(f"| {p} | " + " | ".join(marks) + " |")
    w("")

# ---------------------------------------------------------------- all runs
w("## Every run on record")
w("")
allrun = []
for f in sorted(glob.glob(os.path.join(ROOT, "results", "*", "summary.json"))):
    rid = os.path.basename(os.path.dirname(f))
    try:
        s = json.load(open(f))
    except ValueError:
        continue
    allrun.append((rid, s))
smoke = [(r, s) for r, s in allrun if r.startswith(("smoke", "ga-smoke", "preflight", "_", "retry-test", "wifi-test"))]
main = [(r, s) for r, s in allrun if (r, s) not in smoke]

w("| run | combo | n | solved | cost_std | finished |")
w("|---|---|---|---|---|---|")
for rid, s in sorted(main, key=lambda x: x[1].get("finished_at") or ""):
    combo = ",".join(s.get("combo") or []) or "base"
    w(f"| {rid} | {combo} | {s.get('problems')} | {s.get('solved')} | "
      f"${(s.get('cost_std') or 0):.2f} | {(s.get('finished_at') or '')[:10]} |")
# in-flight
for name, (d, done, tot) in cells.items():
    if not done and d:
        for rid in CELLS[name]:
            if summary(rid) is None and rows(rid):
                rr = rows(rid)
                w(f"| {rid} | *in flight* | {tot} | {sum(1 for r in rr if r['solved'])} (of "
                  f"{len(rr)} done) | ${sum(r.get('cost_std') or 0 for r in rr):.2f} | — |")
w("")
sm = sum((s.get("cost_std") or 0) for _, s in smoke)
w(f"Plus {len(smoke)} smoke/probe runs totalling ${sm:.2f}.")
w("")

grand = sum((s.get("cost_std") or 0) for _, s in allrun)
inflight = sum(sum(r.get("cost_std") or 0 for r in rows(rid))
               for name, (d, done, _) in cells.items() if not done
               for rid in CELLS[name] if summary(rid) is None)
w(f"**Total cost_std across every run: ${grand + inflight:.2f}** "
  f"(${grand:.2f} finished + ${inflight:.2f} in flight).")
w("")

open(OUT, "w").write("\n".join(L) + "\n")
print(f"wrote {OUT} ({len(L)} lines)")
